// ReportDetail page (CP20D): preview + summary + HITL timeline + submit-for-review / archive.
import { useCallback, useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { reportService } from "../services/reportService";
import { useAuth } from "../context/AuthContext";
import Loading from "../components/Loading";
import ErrorMessage from "../components/ErrorMessage";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import ReportStatusBadge from "../components/reports/ReportStatusBadge";
import ReportPreview from "../components/reports/ReportPreview";
import ReportSummaryCard from "../components/reports/ReportSummaryCard";
import ReportTimeline from "../components/reports/ReportTimeline";
import SubmitForReviewButton from "../components/reports/SubmitForReviewButton";
import ArchiveButton from "../components/reports/ArchiveButton";

const MANAGE_ROLES = ["super_admin", "jpn_admin", "executive"];

export default function ReportDetail() {
  const { id } = useParams();
  const { hasRole } = useAuth();
  const canManage = hasRole(...MANAGE_ROLES);

  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const [actionMsg, setActionMsg] = useState(null);
  const [actionError, setActionError] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setReport(await reportService.get(id));
    } catch (err) {
      setError(err.message || "Failed to load report.");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => { load(); }, [load]);

  async function onSubmit() {
    setBusy(true); setActionError(null); setActionMsg(null);
    try {
      const res = await reportService.submitForReview(id);
      setActionMsg(`Submitted for review (approval state: ${res.approval_state}). Awaiting an authorised officer.`);
      await load();
    } catch (err) { setActionError(err.message || "Submit failed."); }
    finally { setBusy(false); }
  }

  async function onArchive() {
    setBusy(true); setActionError(null); setActionMsg(null);
    try {
      await reportService.archive(id);
      setActionMsg("Report archived.");
      await load();
    } catch (err) { setActionError(err.message || "Archive failed."); }
    finally { setBusy(false); }
  }

  if (loading) return <Loading label="Loading report…" />;
  if (error) return (
    <div className="space-y-3">
      <ErrorMessage message={error} />
      <Link to="/app/reports" className="text-sm text-blue-700 hover:underline">← Back to reports</Link>
    </div>
  );

  return (
    <div className="space-y-6">
      <Link to="/app/reports" className="text-sm text-blue-700 hover:underline">← Back to reports</Link>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>{report.title || "Report"}</CardTitle>
          <ReportStatusBadge status={report.status} />
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-3">
            <div><p className="text-xs uppercase tracking-wide text-slate-400">Period</p><p className="text-slate-700">{report.period || "—"}</p></div>
            <div><p className="text-xs uppercase tracking-wide text-slate-400">Type</p><p className="text-slate-700">{report.type || "—"}</p></div>
            <div><p className="text-xs uppercase tracking-wide text-slate-400">Generated By</p><p className="truncate text-slate-700">{report.generated_by || "—"}</p></div>
          </div>

          <div className="flex flex-wrap items-center gap-3 pt-2">
            <SubmitForReviewButton status={report.status} canManage={canManage} submitting={busy} onSubmit={onSubmit} />
            <ArchiveButton status={report.status} canManage={canManage} archiving={busy} onArchive={onArchive} />
            {!canManage && <span className="text-xs text-slate-500">You have view-only access to this report.</span>}
          </div>
          {actionMsg && <div className="rounded-md border border-green-200 bg-green-50 px-3 py-2 text-sm text-green-700">{actionMsg}</div>}
          {actionError && <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{actionError}</div>}
        </CardContent>
      </Card>

      <ReportTimeline status={report.status} rejectReason={report.reject_reason} />

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <ReportPreview report={report} />
        <ReportSummaryCard content={report.content} />
      </div>
    </div>
  );
}
